#(Ejercicio10)
#(Cree un programa que lea dos valoresnehteros, a y b, introducidos por el usuari. Su programa debe desplegar.)
#(La suma a y b)
#(La diferencia cunado a es sustraido a b)
#(El producto de a y b)
#(El cociente cuando a divide b)
#(El residuo cuando a divide a b)
#(El resultado de log(a))
#(El resultado de a a la potencia de b)
#(Tip: utilice la libreria math)
import math
a=int(input('Ingrese valor de a '))
b=int(input('ingrse valor de b '))
print('suma', a+b)
print('diferencia', a-b)
print('producto', a*b)
print('cociente', a / b)
print('residuo', a % b)
print('logaritmo', math.log(a))
print('potencia', math.pow(a, b))